---
- name: Check Asterisk Server Uptime
  hosts: asteriskec2
  gather_facts: yes
  tasks:
    - name: Get uptime in minutes
      shell: echo $(awk '{print $1}' /proc/uptime) / 60 | bc
      register: uptime_output

    - name: Display uptime in minutes
      debug: 
        msg: "Current Uptime is : {{ uptime_output.stdout }} min"

    - name: Pass variable to Jenkins
      set_fact:
        jenkins_var_uptime: "{{ uptime_output.stdout }}"
        jenkins_var_value: "{{ lookup('pipe', 'echo {{ jenkins_var_uptime }}') }}" 
...  
