---
- name: Check Asterisk Server Uptime
  hosts: asteriskec2
  gather_facts: yes
  tasks:
    - name: Get uptime in minutes
      shell: echo $(awk '{print $1}' /proc/uptime) / 60 | bc
      register: uptime_output

    - name: Display uptime in minutes
      debug: 
        msg: "Current Uptime is : {{ uptime_output.stdout }} min"

- name: Update uptime in result.txt
  hosts: hostmachine
  vars:
    fpath: "{{ lookup('env','fpath') }}"
    password: "{{ lookup('env','password') }}"
  tasks:
    - name: Update uptime in result.txt
      lineinfile:
        path: "{{ fpath }}/result.txt"
        regexp: '^uptime_in_min=(.*)$'
        line: "uptime_in_min={{ uptime_output.stdout }}"
        backrefs: yes
      become_user: jenkins
...  
