---
- name: Reboot Asterisk Server
  hosts: asteriskec2
  gather_facts: no
  tasks:
    - name: Reboot the Server
      #shell: aws ec2 reboot-instances --instance-ids i-0c23fa871d3788d77 --region ap-south-1
      #shell: /sbin/shutdown -r now
      #shell: "sleep 5 && reboot"
      #async: 1
      #poll: 0
        #tags: reboot
        #become: yes
      reboot:
        #become: yes  
        #become_user: root

    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 180

    - name: Get uptime in minutes
      shell: echo $(awk '{print $1}' /proc/uptime) / 60 | bc
      register: uptime_output

    - name: Display uptime in minutes
      debug:
        msg: "Current Uptime is : {{ uptime_output.stdout }} min"
...
